
server:
  port: 8086
#  servlet:
#    context-path: /pro5
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
    hidden-method:
      filter:
        enabled: true
    static-path-pattern: /static/**
    # css js 파일 위치

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tsherpa_my
    username: root
    password: 1234

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#    html -> static (데이터 바인딩 불가) / Thymeleaf 쓰는 문서는 모두 static
mybatis:
  type-aliases-package: com.chunjae.proeject05.entity
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml